"""
Simplified server - Using Doubao API
Process: Upload → SAM segmentation → Doubao Inpainting → Return results
"""
import os
import sys
import base64
from pathlib import Path
from fastapi import FastAPI, UploadFile, File, Form, HTTPException
from fastapi.middleware.cors import CORSMiddleware
import uuid
from PIL import Image
import numpy as np
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Add SAM2 path
sys.path.append(os.path.join(os.path.dirname(__file__), "sam2"))

# Import modules
from sam import SAM2Handler
from inpainting_doubao import DoubaoInpainter

# Initialize FastAPI
app = FastAPI(title="Spatial Shift - Doubao API")

# CORS configuration
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Directory setup
UPLOAD_DIR = Path("uploads")
OUTPUT_DIR = Path("output")
UPLOAD_DIR.mkdir(exist_ok=True)
OUTPUT_DIR.mkdir(exist_ok=True)
(OUTPUT_DIR / "masks").mkdir(exist_ok=True)
(OUTPUT_DIR / "furniture").mkdir(exist_ok=True)
(OUTPUT_DIR / "backgrounds").mkdir(exist_ok=True)

# Initialize models
print("\n" + "="*50)
print("🚀 Spatial Shift simplified version starting")
print("="*50 + "\n")

# SAM initialization
sam_handler = SAM2Handler(
    checkpoint_path="checkpoints/sam2.1_hiera_large.pt",
    model_config="configs/sam2.1/sam2.1_hiera_l.yaml"
)

# Doubao Inpainting initialization
try:
    doubao_inpainter = DoubaoInpainter()
except Exception as e:
    print(f"⚠️  Doubao API initialization failed: {e}")
    print("   Please ensure ARK_API_KEY is set in .env file")
    doubao_inpainter = None

print("\n✅ Spatial Shift simplified version started successfully!")
print("   - SAM 2.1 segmentation")
print("   - Doubao API Inpainting")
print(f"   - Service address: http://0.0.0.0:8001\n")


@app.get("/")
def root():
    """Health check"""
    return {
        "status": "running",
        "version": "doubao-simplified",
        "features": ["sam-segmentation", "doubao-inpainting"]
    }


@app.post("/upload")
async def upload_image(file: UploadFile = File(...)):
    """
    Upload image
    """
    try:
        # Generate unique ID
        image_id = str(uuid.uuid4())
        file_ext = Path(file.filename).suffix or ".jpg"
        file_path = UPLOAD_DIR / f"{image_id}{file_ext}"
        
        # Save file
        with open(file_path, "wb") as f:
            content = await file.read()
            f.write(content)
        
        print(f"📁 Image uploaded: {file_path}")
        return {"image_id": image_id, "filename": file.filename}
    
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Upload failed: {str(e)}")


@app.post("/process")
async def process_image(
    image_id: str = Form(...),
    click_x: int = Form(...),
    click_y: int = Form(...),
    place_x: int = Form(...),
    place_y: int = Form(...)
):
    """
    Complete pipeline: SAM segmentation → Doubao generates movement effect image
    
    Args:
        image_id: Image ID
        click_x: X coordinate of furniture click
        click_y: Y coordinate of furniture click
        place_x: X coordinate of target position
        place_y: Y coordinate of target position
    
    Returns:
        {
            "furniture_mask": "base64_image",  # Segmented mask
            "final_image": "base64_image"  # Movement effect image generated by Doubao
        }
    """
    try:
        # 1. Find original image
        image_files = list(UPLOAD_DIR.glob(f"{image_id}.*"))
        if not image_files:
            raise HTTPException(status_code=404, detail="Image not found")
        
        image_path = str(image_files[0])
        print(f"\n{'='*50}")
        print(f"🎯 Starting to process image: {image_path}")
        print(f"   Furniture position: ({click_x}, {click_y})")
        print(f"   Target position: ({place_x}, {place_y})")
        print(f"{'='*50}\n")
        
        # 2. SAM segmentation
        furniture_output = OUTPUT_DIR / "furniture" / f"{image_id}_furniture.png"
        result_path, score, related_count = sam_handler.process_segmentation_smart(
            image_path, click_x, click_y, str(furniture_output)
        )
        print(f"✅ SAM segmentation complete, confidence: {score:.3f}, related objects: {related_count}")
        
        # 3. Extract mask
        furniture_img = Image.open(result_path)
        if furniture_img.mode == 'RGBA':
            mask_array = np.array(furniture_img.split()[-1])
        else:
            mask_array = np.array(furniture_img.convert('L'))
        
        # Save mask
        mask_output = OUTPUT_DIR / "masks" / f"{image_id}_mask.png"
        mask_img = Image.fromarray(mask_array, mode='L')
        mask_img.save(mask_output)
        print(f"📦 Mask saved: {mask_output}")
        
        # 4. Doubao generates movement effect image
        if not doubao_inpainter:
            raise HTTPException(status_code=500, detail="Doubao API not initialized")
        
        final_output = OUTPUT_DIR / "backgrounds" / f"{image_id}_final.png"
        final_path = doubao_inpainter.inpaint(
            image_path,
            str(mask_output),
            str(final_output),
            target_x=place_x,
            target_y=place_y
        )
        
        # 5. Convert to base64 and return
        def image_to_base64(img_path):
            with open(img_path, "rb") as f:
                return base64.b64encode(f.read()).decode()
        
        mask_b64 = image_to_base64(mask_output)
        final_b64 = image_to_base64(final_path)
        
        print(f"\n✅ Processing complete!")
        print(f"{'='*50}\n")
        
        return {
            "image_id": image_id,
            "furniture_mask": mask_b64,
            "final_image": final_b64,
            "confidence": float(score),
            "related_objects": related_count,
            "target_position": {"x": place_x, "y": place_y}
        }
    
    except Exception as e:
        print(f"\n❌ Processing failed: {str(e)}\n")
        raise HTTPException(status_code=500, detail=f"Processing failed: {str(e)}")


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("origin:app", host="0.0.0.0", port=8001, reload=True)
